# Generated by Django 4.2.2 on 2024-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='walletAddress',
            field=models.CharField(default=123, max_length=42),
            preserve_default=False,
        ),
    ]
